name: BPF checks

on:
  pull_request: {}
  push:
    branches:
      - v1.8

jobs:
    coccicheck:
        name: coccicheck
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.3.0
            - uses: docker://cilium/coccicheck:1.0
              with:
                entrypoint: ./contrib/coccinelle/check-cocci.sh
